import { StateSchema, MessagesValue, type GraphNode, StateGraph, START, END, type CompiledStateGraph} from "@langchain/langgraph";
import * as z from 'zod';
import { cohereModel, geminiModel, mistralMOdel } from "./model.ai.js";
import { createAgent, HumanMessage, providerStrategy, ProviderStrategy } from "langchain";

// State Schema Definition
const state  = new StateSchema({
    messages: MessagesValue,
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
});

// Node Definitions
const solutionNode:GraphNode<typeof state> = async (state) =>{
    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralMOdel.invoke(state.problem),
        cohereModel.invoke(state.problem),
    ]);

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}

const judgeNode:GraphNode<typeof state> = async (state) => {
    const {problem, solution_1, solution_2} = state;

    // To get response in structure formate
    // NOTE:- toolStrategy when use another ai insted of Gemini instead of providerStrategy
    const judgeAgent = createAgent({
        model: geminiModel,
        tools: [],
        responseFormat: providerStrategy(
            z.object({
                solution_1_score: z.number().min(0).max(10),
                solution_2_score: z.number().min(0).max(10),
                solution_1_reasoning: z.string().default(""),
                solution_2_reasoning: z.string().default(""),
            })
        ),
        systemPrompt: `You are a judge tasked with evaluating two solutions 
        generated by different ai models. The problem is: ${problem}. 
        Please provide a score between 0 and 10 for each solution, along with 
        the score must vary between 0 to 10. provide 10 only if answer is perfect and 
        try not to provide all 10 to both solution. Also, provide detailed reasoning for the scores you assign to each solution. 
        your reasoning for the scores.
        Solution 1: ${solution_1}
        Solution 2: ${solution_2}`,
    })

    const judgeResponse = await judgeAgent.invoke({
        messages: [
            new HumanMessage(`
                Problem: ${problem},
                Solution 1: ${solution_1},
                Solution 2: ${solution_2},
                Please evaluate the solutions and provide scores and reasoning.
            `)
        ]
    });

    const { 
        solution_1_score, 
        solution_2_score, 
        solution_1_reasoning, 
        solution_2_reasoning 
    } = judgeResponse.structuredResponse;

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning,
        }
    }

}


// Graph Construction
const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("ai_judge", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "ai_judge")
    .addEdge("ai_judge", END)
    .compile();

export default async function runGraph(problem: string) {
    const result = await graph.invoke({
        problem: problem
    });
    return result;
}

